- menu_name: 'Services'

- name: 'Impressum'
  url: '/impressum/'
  title: 'Impressum'

- name: 'Kontakt'
  url: '/kontakt/'
  title: 'Kontakt'

- name: 'RSS Feed'
  url: '/feed.xml'
  title: 'RSS Feed abonnieren'

- name: 'Atom Feed'
  url: '/atom.xml'
  title: 'Atom Feed abonnieren'

- name: 'sitemap.xml'
  url: '/sitemap.xml'
  title: 'Sitemap für Google Webmaster Tools'
